const baseUrl = 'http://192.168.10.247:8888';  

const ApiConfig = {
  login: '/login',
  sendEmailLogin: '/sendEmailLogin',
  sendEmailLoginAgain: '/sendEmailLoginAgain',
  registerCheck:'/registerCheck',
  registerConfirmAgain:'/registerConfirmAgain',
  register:'/register',
  sendEmailAgainForgotPass:'/sendEmailAgainForgotPass',
  setNewPassword:'/setNewPassword',
  checkCode:'/checkCode',
  checkAcount:'/checkAcount',
  setNewPassword:'/setNewPassword',
  createVBPL:'/createVBPL',
  getAdmin: (id) => `/getUserById/${id}`,
  getAllVBPL:'/getAllVBPL',
  getTTUser:(idUser) => `/TTUser/${idUser}`,
  getVBPL: (id) => `/getVBPL/${id}`,
  getAllUser:'/admin/getAlluser',
  getTTAdmin: (id) => `/TTNV/get/${id}`,
  getUserById: (id) => `/getUserById/${id}`,
  getMaXacNhanByCCCD:(cccd) => `/getMaXacNhanByCCCD/${cccd}`,
  getAllHoSoByCCCD:(cccd)=>`/getAllHoSoByCCCD/${cccd}`,
  updateVBPL: '/updateVBPL',
  createTTAdmin:'/TTNV/create',
  updateTTAdmin:'/TTNV/update', 
  updateUser:'/admin/updateUser',
  createManager:'/admin/createManager',
  filter:'/FilterUser',
  thongkeUser:'/ThongKeUser',
  oderByHigh:'/ThongKeUserGiamDan',
  oderByLow:'/ThongKeUserTangDan',
 // createManager:'/admin/createUser',
  createGiaHanTamTru : '/GiaHanTamTru/create',
  updatethongtinuser:'/TTUser/update',
  khaibaotamtru:'/KhaiBaoTamTru/create',
  khaibaothuongtru :'/KhaiBaoThuongTru/create',
  thongbaoluutru :'/ThongBaoLuuTru/create',
  napthutucgiahantamtru: '/GiaHanTamTru/create',
  getGiaHanTamTru:(id)=>`/GiaHanTamTru/${id}`,
  putGiaHanTamTru: `/GiaHanTamTru/update`,
  getKhaiBaoTamTru:(id)=>`/KhaiBaoTamTru/${id} `,
  putKhaiBaoTamTru: `/KhaiBaoTamTru/update`,
  getKhaiBaoTamVang:(id)=>`/KhaiBaoTamVang/${id}`,
  putKhaiBaoTamVang: `/KhaiBaoTamVang/update`,
  getKhaiBaoThuongTru:(id)=>`/KhaiBaoThuongTru/${id} `,
  putKhaiBaoThuongTru: `/KhaiBaoThuongTru/update`,
  getThongBaoLuuTru:(id)=>`/ThongBaoLuuTru/${id} `,
  putThongBaoLuuTru: `/ThongBaoLuuTru/update`,
  getXoaDangKyThuongTru:(id)=>`/XoaDangKyThuongTru/${id}`,
  putXoaDangKyThuongTru: `/XoaDangKyThuongTru/update`,
  getXoaDangKyTamTru:(id)=>`/XoaDangKyTamTru/${id}`,
  putXoaDangKyTamTru: `/XoaDangKyTamTru/update`,
  getThongTinUser: (id) => `/TTUser/${id}`,
  getTinhThanhPho: (tinhThanhPho) =>`/ThongKeUser/${tinhThanhPho}`,
  getHuyen:(tinhThanhPho,huyen)=>`/ThongKeUser/${tinhThanhPho}/${huyen}`,
  ThongKeUserFilter:(filter)=>`/ThongKeUserFilter/${filter}`,
  getDonPheDuyet:`/employee/donPheDuyet`,
  getAllHoSoCheckingByCoQuan:`/getAllHoSoCheckingByCoQuan`,

  
};

export const apiUrl = (endpoint) => {
  return baseUrl + endpoint;
};

export default ApiConfig;